### ISSUE TITLE
Datasets with other dimensions

### ISSUE THREAD

**Issue by pfreitasaf** [houssamzenati/Adversarially-Learned-Anomaly-Detection#1]
Hello Mr.,

First of all, congratulations on your work! It is very interesting and insightful.
I was able to run your code with the kddcup99 dataset. However, I would like to know if you could give me some help and directions on how to adapt your code for other datasets with different dimensions. For example, what I would have to do if I want to use only a few features of the kddcup99 dataset, so I have  15 features instead of 121?

Thank you very much for your help and assistance!
Best regards,
Paulo

**Comment by houssamzenati** [comment]
Hi @pfreitasaf and thank you for reaching out, please see my response in my other repositery and do let me know if you need extra help
